### PR TITLE
Move all tests to tests dir

### PR DESCRIPTION
**Pull request by steve-chavez**

### CODE REVIEW

**Comment by ruslantalpa** [comment]
maybe better change `./tests/openresty/rest/` to `./tests/rest/`

**Comment by steve-chavez** [comment]
Those tests target `http://localhost:8080/rest`, endpoint defined by openresty, if the folder just says `tests/rest` is not obvious if we are testing `postgrest/openresty` endpoints. Don't see the gain there.

**Comment by ruslantalpa** [comment]
the rest interface does not necesarily depend on openresty, we can just as well have tests there going to postgrest:3000

**Comment by steve-chavez** [comment]
When that happens then those tests should be moved to the `/tests/postgrest` dir,  the `tests` structure now makes more sense when differentiating the `openresty/postgrest` components. If the `/tests/postgrest` contents is removed then having just `/tests/rest` will make sense.

**Comment by ruslantalpa** [comment]
`/tests/postgrest` should be removed.
the tests started with the idea of each component being tested but now i am thinking about them as
`db tests` or `integration tests (aka rest/graphql test)` so they are less about a component in the stack and mor about a specific functionality/area exposed by the stack

**Comment by steve-chavez** [comment]
Created the `/tests/rest` dir and removed `/tests/postgrest`, guess it's fine since the bash tests were failing anyway.

**Pull request merged**
